const { Post } = require("../models");

const postdata = [
  {
    title: "Donec posuere metus vitae ipsum.",
    content:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...",
    user_id: 10,
    dog_name: "Scout",
    energy: "High Energy",
    vaccine: "Yes",
    human_interaction: "Some",
    breed: "Mutt",
  },
  {
    title: "Morbi non quam nec dui luctus rutrum.",
    content: "Nam nisl ipsum, bibendum ac.",
    user_id: 8,
    dog_name: "Duke",
    energy: "High Energy",
    vaccine: "Some",
    human_interaction: "Some",
    breed: "Rhodesian Ridgeback",
  },
  {
    title:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    content: "Donec malesuada augue eu venenatis.",
    user_id: 1,
    dog_name: "Bella",
    energy: "Mellow",
    vaccine: "Yes",
    human_interaction: "No",
    breed: "French Bulldog",
  },
  {
    title: "Nunc purus.",
    content: "Nam bibendum elementum arcu ac.",
    user_id: 4,
    dog_name: "Sebastian",
    energy: "High Energy",
    vaccine: "Yes",
    human_interaction: "Yes",
    breed: "French Bulldog",
  },
  {
    title: "Pellentesque eget nunc.",
    content: "Pellentesque finibus nibh eu nibh.",
    user_id: 7,
    dog_name: "Blake",
    energy: "Mellow",
    vaccine: "No",
    human_interaction: "No",
    breed: "Lab",
  },
  {
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    content: "Aenean purus magna, posuere a.",
    user_id: 4,
    dog_name: "Bailey",
    energy: "High Energy",
    vaccine: "Yes",
    human_interaction: "Yes",
    breed: "Lab",
  },
  {
    title: "In hac habitasse platea dictumst.",
    content: "Ut vehicula a enim et.",
    user_id: 1,
    dog_name: "Abbie",
    energy: "In Between",
    vaccine: "Some",
    human_interaction: "No",
    breed: "Mutt",
  },
  {
    title: "Morbi non quam nec dui luctus rutrum.",
    content: "Nulla lobortis elit vitae risus.",
    user_id: 1,
    dog_name: "Max",
    energy: "High Energy",
    vaccine: "No",
    human_interaction: "Yes",
    breed: "Shit-Zu",
  },
  {
    title: "Duis ac nibh.",
    content: "Mauris mi purus, ornare in sapien non, pulvinar placerat sem.",
    user_id: 9,
    dog_name: "Dodger",
    energy: "Mellow",
    vaccine: "Yes",
    human_interaction: "Yes",
    breed: "Mutt",
  },
  {
    title: "Curabitur at ipsum ac tellus semper interdum.",
    content: "Aliquam mollis posuere bibendum.",
    user_id: 5,
    dog_name: "Herbie",
    energy: "In Between",
    vaccine: "No",
    human_interaction: "No",
    breed: "Yorkshire Terrier",
  },
  {
    title: "In hac habitasse platea dictumst.",
    content:
      " Nam semper, nunc at feugiat porta, metus arcu molestie lorem, sit amet gravida nulla velit sit amet est.",
    user_id: 3,
    dog_name: "Charlie",
    energy: "Mellow",
    vaccine: "Yes",
    human_interaction: "Some",
    breed: "Terrier",
  },
  {
    title: "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    content: "Aliquam interdum metus vel tincidunt pretium.",
    user_id: 10,
    dog_name: "Jazzy",
    energy: "High Energy",
    vaccine: "Some",
    human_interaction: "Yes",
    breed: "Poodle",
  },
  {
    title: "Donec dapibus.",
    content:
      "Vestibulum tortor est, tincidunt id accumsan at, efficitur at massa.",
    user_id: 8,
    dog_name: "Rufus",
    energy: "High Energy",
    vaccine: "No",
    human_interaction: "Yes",
    breed: "Bloodhound",
  },
  {
    title: "Nulla tellus.",
    content: "Etiam rutrum laoreet purus, id congue leo faucibus vitae.",
    user_id: 3,
    dog_name: "Radar",
    energy: "In Between",
    vaccine: "Yes",
    human_interaction: "Some",
    breed: "Husky",
  },
  {
    title:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    content: "Sed tincidunt lacus ac dui ornare, ac blandit eros feugiat.",
    user_id: 3,
    dog_name: "Bing",
    energy: "High Energy",
    vaccine: "Yes",
    human_interaction: "No",
    breed: "Husky",
  },
  {
    title:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    content: "Donec placerat sollicitudin orci non gravida.",
    user_id: 7,
    dog_name: "Chewie",
    energy: "In Between",
    vaccine: "Yes",
    human_interaction: "Yes",
    breed: "Mutt",
  },
  {
    title: "In hac habitasse platea dictumst.",
    content: "Morbi dictum arcu nunc, et hendrerit ligula porttitor eget.",
    user_id: 6,
    dog_name: "Biscuit",
    energy: "Mellow",
    vaccine: "No",
    human_interaction: "Yes",
    breed: "English Bulldog",
  },
  {
    title: "Etiam justo.",
    content: "Aliquam interdum metus vel tincidunt pretium.",
    user_id: 4,
    dog_name: "Gary",
    energy: "High Energy",
    vaccine: "Yes",
    human_interaction: "No",
    breed: "German Shepherd",
  },
  {
    title: "Nulla ut erat id mauris vulputate elementum.",
    content: "Sed egestas porta metus, at mollis libero.",
    user_id: 6,
    dog_name: "Coco",
    energy: "Mellow",
    vaccine: "Some",
    human_interaction: "Some",
    breed: "Chihuahua",
  },
  {
    title:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    content:
      "Suspendisse justo est, elementum non nunc non, scelerisque convallis nisi.",
    user_id: 7,
    dog_name: "Fiona",
    energy: "In Between",
    vaccine: "Some",
    human_interaction: "No",
    breed: "Mutt",
  },
];

const seedPosts = () => Post.bulkCreate(postdata);

module.exports = seedPosts;
